{ ... }: {
  imports = [
    ./aerial
    ./comment
    ./dashboard
    ./eyeliner
    ./git
    ./grug-far
    ./highlight-undo-nvim
    ./illuminate
    ./indent-blankline
    ./leap
    ./lualine
    ./luasnip
    ./neo-tree
    ./nvim-highlight-colors
    ./nvim-surround
    ./oil
    ./rainbow-delimiters
    ./telescope
    ./todo-comments
    ./transparent
    ./treesitter
    ./trouble
    ./undotree
    ./vimtex
    ./web-devicons
    ./which_key
    ./yazi
  ];
}
