"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$character
"""

right_format = """
$git_branch\
$git_status\
$cmd_duration
"""

palette = 'eldritch'

[directory]
style = "bg:bg fg:base06"
format = "[ $path ]($style)"
home_symbol = '~'
truncate_to_repo = true
truncation_symbol = '…/'

[character]
disabled = false
success_symbol = '[ \$ ](bg:surface0 bold fg:base02)'
error_symbol = '[ \$ ](bg:surface0 bold fg:base01)'
vimcmd_symbol = '[ V ](bg:surface0 bold fg:base06)'
vimcmd_replace_one_symbol = '[ r ](bg:surface0 bold fg:base13)'
vimcmd_replace_symbol = '[ R ](bg:surface0 bold fg:base13)'
vimcmd_visual_symbol = '[ V ](bg:surface0 bold fg:base12)'

# ZVM_MODE_NORMAL = '[ N ](bg:surface0 bold fg:base06)'
# ZVM_MODE_INSERT = '[ I ](bg:surface0 bold fg:base02)'
# ZVM_MODE_VISUAL = '[ V ](bg:surface0 bold fg:base12)'
# ZVM_MODE_VISUAL_LINE = '[ V ](bg:surface0 bold fg:base12)'
# ZVM_MODE_REPLACE = '[ R ](bg:surface0 bold fg:base13)'

[git_branch]
style = "bg:bg fg:base12"
format = '[$symbol $branch]($style)'
symbol = ''

[git_status]
style = "bg:bg"
format = '[$ahead_behind$modified$staged$untracked]($style)'
ahead = '[ ⇡${count}](fg:base03)'
behind = '[ ⇣${count}](fg:base03)'
diverged = '[ ⇕${count}](fg:base03)'
up_to_date = ''
modified = '[ !${count}](fg:base01)'
staged = '[ +${count}](fg:base02)'
untracked = '[ ?${count}](fg:base06)'

[cmd_duration]
show_milliseconds = true
format = '[ 󰔟$duration]($style)'
style = "bg:bg fg:base13"
disabled = false
min_time = 0
show_notifications = false
min_time_to_notify = 30_000

[line_break]
disabled = false

[palettes.eldritch]
base00    = "#21222C"
base01    = "#F9515D"
base02    = "#37F499"
base03    = "#E9F941"
base04    = "#9071F4"
base05    = "#F265B5"
base06    = "#04D1F9"
base07    = "#EBFAFA"
base08    = "#7081D0"
base09    = "#F16C75"
base10    = "#69F8B3"
base11    = "#F1FC79"
base12    = "#A48CF2"
base13    = "#FD92CE"
base14    = "#66E4FD"
base15    = "#FFFFFF"
fg        = "#ebfafa"
bg        = "#212337"
text      = "#CDD6F4"
subtext1  = "#BAC2DE"
subtext0  = "#A6ADC8"
overlay2  = "#9399B2"
overlay1  = "#7F849C"
overlay0  = "#6C7086"
surface2  = "#585B70"
surface1  = "#45475A"
surface0  = "#313244"
base      = "#1E1E2E"
mantle    = "#181825"
crust     = "#11111B"

[palettes.catppuccin_mocha]
rosewater = "#F5E0DC"
flamingo  = "#F2CDCD"
pink      = "#F5C2E7"
mauve     = "#CBA6F7"
red       = "#F38BA8"
maroon    = "#EBA0AC"
peach     = "#FAB387"
yellow    = "#F9E2AF"
green     = "#A6E3A1"
teal      = "#94E2D5"
sky       = "#89DCEB"
sapphire  = "#74C7EC"
blue      = "#89B4FA"
lavender  = "#B4BEFE"
text      = "#CDD6F4"
subtext1  = "#BAC2DE"
subtext0  = "#A6ADC8"
overlay2  = "#9399B2"
overlay1  = "#7F849C"
overlay0  = "#6C7086"
surface2  = "#585B70"
surface1  = "#45475A"
surface0  = "#313244"
base      = "#1E1E2E"
mantle    = "#181825"
crust     = "#11111B"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo  = "#eebebe"
pink      = "#f4b8e4"
mauve     = "#ca9ee6"
red       = "#e78284"
maroon    = "#ea999c"
peach     = "#ef9f76"
yellow    = "#e5c890"
green     = "#a6d189"
teal      = "#81c8be"
sky       = "#99d1db"
sapphire  = "#85c1dc"
blue      = "#8caaee"
lavender  = "#babbf1"
text      = "#c6d0f5"
subtext1  = "#b5bfe2"
subtext0  = "#a5adce"
overlay2  = "#949cbb"
overlay1  = "#838ba7"
overlay0  = "#737994"
surface2  = "#626880"
surface1  = "#51576d"
surface0  = "#414559"
base      = "#303446"
mantle    = "#292c3c"
crust     = "#232634"

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo  = "#dd7878"
pink      = "#ea76cb"
mauve     = "#8839ef"
red       = "#d20f39"
maroon    = "#e64553"
peach     = "#fe640b"
yellow    = "#df8e1d"
green     = "#40a02b"
teal      = "#179299"
sky       = "#04a5e5"
sapphire  = "#209fb5"
blue      = "#1e66f5"
lavender  = "#7287fd"
text      = "#4c4f69"
subtext1  = "#5c5f77"
subtext0  = "#6c6f85"
overlay2  = "#7c7f93"
overlay1  = "#8c8fa1"
overlay0  = "#9ca0b0"
surface2  = "#acb0be"
surface1  = "#bcc0cc"
surface0  = "#ccd0da"
base      = "#eff1f5"
mantle    = "#e6e9ef"
crust     = "#dce0e8"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo  = "#f0c6c6"
pink      = "#f5bde6"
mauve     = "#c6a0f6"
red       = "#ed8796"
maroon    = "#ee99a0"
peach     = "#f5a97f"
yellow    = "#eed49f"
green     = "#a6da95"
teal      = "#8bd5ca"
sky       = "#91d7e3"
sapphire  = "#7dc4e4"
blue      = "#8aadf4"
lavender  = "#b7bdf8"
text      = "#cad3f5"
subtext1  = "#b8c0e0"
subtext0  = "#a5adcb"
overlay2  = "#939ab7"
overlay1  = "#8087a2"
overlay0  = "#6e738d"
surface2  = "#5b6078"
surface1  = "#494d64"
surface0  = "#363a4f"
base      = "#24273a"
mantle    = "#1e2030"
crust     = "#181926"
