##===========================================##
##=== Filesystem ============================##
library: ~/Music/.data/library.db
directory: ~/Music
art_filename: cover

ignore:
  musicStagingGround
  .*

import:
  write: yes
  copy: no
  move: yes
  incremental: yes
  incremental_skip_later: yes
  log: ~/Music/.data/log

paths:
  default: $albumartist/$album%aunique{}/$track $title
  singleton: Non-Album/$artist/$title
  comp: Compilations/$album%aunique{}/$track $title

##===========================================##
##=== Metadata ==============================##

##===========================================##
##=== Plugins ===============================##
plugins: fetchart

fetchart:
  lastfm_key: c071b447b9ac5524d638e497fdf89035
  sources: lastfm coverart itunes amazon albumart filesystem
  auto: yes
  enforce_ratio: no
  maxwidth: 1000
  cautious: true
  minwidth: 300
  cover_names: cover cover.jpg cover.png

embedart:
  auto: no

##===========================================##
##=== Performance ===========================##
threaded: yes
