{ ... }: {
  imports = [
    ./modules/beeper
    ./modules/bookmarks
    ./modules/discord
    ./modules/dunst
    ./modules/email
    ./modules/firefox
    ./modules/foot
    ./modules/gaming
    ./modules/git
    ./modules/gpg
    ./modules/hyprland
    ./modules/hyprlock
    ./modules/latex
    ./modules/libreoffice
    ./modules/mpv
    ./modules/music
    ./modules/nautilus
    ./modules/neovim
    ./modules/obs
    ./modules/passwords
    ./modules/school
    ./modules/shell
    ./modules/slack
    ./modules/swayimg
    ./modules/teams
    ./modules/theme
    ./modules/waybar
    ./modules/waycorner
    ./modules/wlogout
    ./modules/wofi
    ./modules/yazi
    ./modules/zathura
    ./modules/zellij
    ./modules/zoom
  ];
}
